USE dog_lister_db;

INSERT INTO breeds (name)
VALUES  ('Airedale Terrier'),
        ('Akita'),
        ('Alaskan Malamute'),
        ('American Eskimo Dog'),
        ('American Pit Bull Terrier'),
        ('Australian Cattle Dog'),
        ('Australian Shepherd'),
        ('Basset Hound'),
        ('Beagle'),
        ('Bernese Mountain Dog'),
        ('Bichon Frise'),
        ('Border Collie'),
        ('Boston Terrier'),
        ('Boxer'),
        ('Brittany'),
        ('Bulldog'),
        ('Cavalier King Charles Spaniel'),
        ('Chihuahua'),
        ('Chinese Crested'),
        ('Chow Chow'),
        ('Cocker Spaniel'),
        ('Dachshund'),
        ('Dalmatian'),
        ('Doberman Pinscher'),
        ('English Cocker Spaniel'),
        ('French Bulldog'),
        ('German Shepherd Dog'),
        ('German Shorthaired Pointer'),
        ('Golden Retriever'),
        ('Great Dane'),
        ('Greyhound'),
        ('Irish Setter'),
        ('Jack Russell Terrier'),
        ('Labrador Retriever'),
        ('Lhasa Apso'),
        ('Maltese'),
        ('Miniature Pinscher'),
        ('Miniature Schnauzer'),
        ('Newfoundland'),
        ('Pekingese'),
        ('Plott Hound'),
        ('Pomeranian'),
        ('Poodle'),
        ('Pug'),
        ('Rottweiler'),
        ('Saint Bernard'),
        ('Shar Pei'),
        ('Shetland Sheepdog'),
        ('Shih Tzu'),
        ('Siberian Husky'),
        ('Weimaraner'),
        ('Whippet'),
        ('Yorkshire Terrier');

INSERT INTO traits (name)
VALUES ('Affectionate'),
       ('Calm'),
       ('Confident'),
       ('Courageous'),
       ('Curious'),
       ('Eager to please'),
       ('Friendly'),
       ('Gentle'),
       ('Good with children'),
       ('Independent'),
       ('Intelligent'),
       ('Lively'),
       ('Loyal'),
       ('Mischievous'),
       ('Obedient'),
       ('Protective'),
       ('Reserved'),
       ('Sensitive'),
       ('Sociable'),
       ('Stubborn'),
       ('Submissive'),
       ('Sweet-tempered'),
       ('Vocal'),
       ('Watchful'),
       ('Well-behaved'),
       ('Willful');

INSERT INTO dogs(name, age, playfulness, socialization, affection, training)
values ('Chupa', '6', '4', '1', '3', '2'),
       ('Snoflake', '2', '3', '3', '3', '4'),
       ('Speed', '1', '4', '4', '3', '4'),
       ('Sniffles', '2', '4', '4', '4', '4');

INSERT INTO ads(title, short_description, description, price, dog_id)
values ('Adorable French Bulldog for sale!', '', '', 2500, 1),
       ('Here comes Snowflake!!', 'The Akita is a popular breed with many unique traits. Learn all about this loyal, intelligent dog', 'Looking for a furry friend who''s loyal, loving, and a little bit quirky? Look no further than the Akita! This pup is sure to steal your heart with their fluffy coat, perky ears, and playful personality. Adopt an Akita today and add some whimsy to your life!', 1500, 2),
       ('You''ve got a need for speed!', 'Often mistaken for the Italian Greyhound, the Whippet is a family-friendly dog.', 'Looking for a furry friend who''s equal parts elegance and goofiness? Meet the Whippet! This sleek and speedy pup loves nothing more than chasing after tennis balls and snuggling up on the couch. Adopt a Whippet today and add some quirkiness to your life!', 1100, 3),
       ('Our sweet sniffles', 'The Plott Hound is North Carolina''s State Dog.', 'Looking for a furry friend who''s as adventurous as you are? Meet the Plot Hound! This brave and loyal pup is always up for exploring the great outdoors and is sure to be your sidekick on any adventure. Adopt a Plot Hound today and add some wildness to your life!', 900, 4);

INSERT INTO dog_breeds(dog_id, breed_id)
VALUES (1,25),
       (2,2),
       (3,51),
       (4,40)


